version: 2
jobs:
   build:
     docker:
       - image: docker:17.05.0-ce-git

     steps:
       - checkout
       - setup_remote_docker
       - run:
            name: Build application Docker image
            command: |
               docker build -t jeddwebill/webilldevops Docker-Test-Services/

       - run:
            name:  list imagesRun Test
            command: |
                            docker run -d --name my-app jeddwebill/webilldevops
                            docker exec -it my-app  curl --retry 10 --retry-connrefused http://localhost:8080
       - run:
                  name:  list Services
                  command: |
                     docker ps
                     echo  $DOCKER_USER

       - deploy:
             name: Deploy Dev to docker
             command: |
               if [ "${CIRCLE_BRANCH}" == "dev-Tests" ]; then
                          docker login -u $DOCKER_USER -p $DOCKER_PASS
                          docker push jeddwebill/webilldevops:latest
               fi