version: 2
jobs:
   build:
     docker:
       - image: docker:17.05.0-ce-git

     steps:
       - checkout
       - setup_remote_docker
       - run:
            name: Build application Docker image
            command: |
               docker build -t app Docker-Test-Services/

       - run:
            name:  list imagesRun Test
            command: |
                            docker run -d --name my-app app node /src/server.js
                            docker ps

       - run:
                  name:  list Services
                  command: |
                      docker exec -it my-app  ping localhost
                      docker ps